### PR TITLE
Re-indented code, and added missing documentations

### PR DESCRIPTION
**Pull request by toksdotdev**
Noticed code was unreadable, so had to re-indent it. Also added descriptions to function parameters that were missing.

### CODE REVIEW

**Comment by JonathanItakpe** [comment]
Thank you. I'd review it later in the evening and do a merge.

**Comment by toksdotdev** [comment]
You are welcome. Also, I'm about to write this same stuff for a different language, I'll need periodic guide on how to implement some things(Though I understand the php version of this library). How can you be contacted.

**Comment by JonathanItakpe** [comment]
Sorry, I was not able to review it yesterday.
Sure, would be willing to help you can hit me up on twitter [@JonathanItakpe](http://twitter.com/JonathanItakpe)

**Comment by toksdotdev** [comment]
???

**Comment by JonathanItakpe** [comment]
Sorry man,... Merged && Released. Thanks

**Pull request merged**
